### ISSUE TITLE
Commissions ? Important 

### ISSUE THREAD

**Issue by OutfitsOG999** [wangzixuank/YimMenu-HeistLua#1]
Are you open to make me a private lua script for recovery purposes and I’ll pay you for it?

**Comment by wangzixuank** [comment]
I make these scripts just for me do Heist, so no payment is necessary.Could you let me know what specific features you're looking for? I'd be happy to see if I can help.

**Comment by OutfitsOG999** [comment]
I was wondering if there was a way to make a script for recovery purposes only such as rank, stats money possibly cars and outfits but mainly money and rank and stats but I would like a safe money loop that is also a high amount also if this isn’t the quickest thing you reply in lmk what I can add you on and I will

**Comment by wangzixuank** [comment]
There are some recovery Lua scripts in this Discord channel. 
https://discord.com/channels/388227343862464513/1123459463320440933

**Comment by OutfitsOG999** [comment]
ik there are decent ones out there but reason I ask for a private script it’s because it will be less abused and less people use it meaning r* will detect it slowly or not at all

**Comment by wangzixuank** [comment]
you need find cheats dev not lua dev,script unalbe to bypass detect. r*  detect cheats not script
